#ifndef BEATS_PLATFORM_BEATSPLATFORM_H__INCLUDE
#define BEATS_PLATFORM_BEATSPLATFORM_H__INCLUDE

#define BEATS_PLATFORM_UNKNOWN 0
#define BEATS_PLATFORM_WIN32  1
#define BEATS_PLATFORM_IOS    2
#define BEATS_PLATFORM_ANDROID 3

#define BEATS_PLATFORM BEATS_PLATFORM_UNKNOWN

#endif