#ifndef BEYOND_ENGINE_EVENT_EVENTTYPE_H__INCLUDE
#define BEYOND_ENGINE_EVENT_EVENTTYPE_H__INCLUDE

enum EEventType
{
    eET_EVENT_MOUSE = 1 << 24,
    eET_EVENT_MOUSE_CLICK,
    eET_EVENT_MOUSE_CLICKED,
    eET_EVENT_MOUSE_PRESSED,
    eET_EVENT_MOUSE_RELEASED,
    eET_EVENT_MOUSE_MOVED,
    eET_EVENT_MOUSE_SCROLLED,

    eET_EVENT_KEYBOARD = 2 << 24,
    eET_EVENT_KEY_PRESSED,
    eET_EVENT_KEY_RELEASED,
    eET_EVENT_KEY_REPEATED,
    eET_EVENT_SIZE_CHANGED,
    eET_EVENT_CHAR,

    eET_EVENT_TOUCH = 3 << 24,
    eET_EVENT_TOUCH_BEGAN,
    eET_EVENT_TOUCH_MOVED,
    eET_EVENT_TOUCH_ENDED,
    eET_EVENT_TOUCH_CANCELLED,
    eET_EVENT_TOUCH_DOUBLE_TAPPED,
    eET_EVENT_TOUCH_SINGLE_TAPPED,
    eET_EVENT_TOUCH_SCORLLED,
    eET_EVENT_TOUCH_PINCHED,

    eET_EVENT_RENDER = 4 << 24,
    eET_EVENT_GUI = 5 << 24,
    eET_EVENT_ANIMATION = 6 << 24,
    eET_EVENT_SCENE = 7 << 24,

    eET_EVENT_NODE_ANIMATION_START = 8 << 24,
    eET_EVENT_NODE_ANIMATION_FINISHED,
    eET_EVENT_NODE_ANIMATION_STOP,

    eET_EVENT_WINDOWCLOSED = 9 << 24,
};

#endif