#ifndef BEYOND_ENGINE_PLATFORM_PLATFOEMDEFINE_INCLUDE
#define BEYOND_ENGINE_PLATFORM_PLATFORMDEFINE_INCLUDE

#define PLATFORM_UNKNOWN 0
#define PLATFORM_WIN32  1
#define PLATFORM_MAC    2
#define PLATFORM_IOS    3
#define PLATFORM_BADA   4
#define PLATFORM_NACL   5
#define PLATFORM_WP8    6
#define PLATFORM_WINRT  7
#define PLATFORM_ANDROID 8

#define BEYONDENGINE_PLATFORM PLATFORM_UNKNOWN



#endif