#ifndef BEYOND_ENGINE_BEYONDENGINEVERSION_H__INCLUDE
#define BEYOND_ENGINE_BEYONDENGINEVERSION_H__INCLUDE

#define BEYONDENGINE_VER_MAJOR 1
#define BEYONDENGINE_VER_MINOR 0
#define BEYONDENGINE_VER_REVISION 20186

#endif //!_VERSION_H_