#1. Set platform folder.

if(WIN32)
    set(PLATFORM_FOLDER win32)
	set(LIB_PREFIX )
	set(LIB_SUFFIX .lib)
elseif(APPLE)
    set(PLATFORM_FOLDER ios)
	set(LIB_PREFIX lib)
	set(LIB_SUFFIX .a)
else()
    set(PLATFORM_FOLDER android)
	set(LIB_PREFIX lib)
	set(LIB_SUFFIX .a)
endif()

#2. Set Define Marco
if(WIN32)
  set(CMAKE_CXX_FLAGS_DEBUG -D_DEBUG " /MDd /Od /ZI")
  set(CMAKE_CXX_FLAGS_RELEASE -DNDEBUG " /MD /O2")
  add_definitions (-DWIN32 -D_WINDOWS)  
  if(MSVC)
  	add_definitions (-D_CRT_SECURE_NO_WARNINGS -D_CRT_NON_CONFORMING_SWPRINTFS -D_SCL_SECURE_NO_WARNINGS -wd4100 -wd4127)
  else(MSVC)  
  endif(MSVC)
elseif(APPLE)
  set(CMAKE_CXX_FLAGS_DEBUG -D_DEBUG)
  set(CMAKE_CXX_FLAGS_RELEASE -DNDEBUG)
  add_definitions(-DAPPLE)
  set(CMAKE_CXX_FLAGS "-std=c++11 -libstdc++")
elseif(ANDROID)
else()#Linux
    add_definitions(-DLINUX)
endif()
