#1. Set platform folder.
include(CheckCXXCompilerFlag)

if(WIN32)
    set(PLATFORM_FOLDER win32)
	set(LIB_PREFIX )
	set(LIB_SUFFIX .lib)
elseif(APPLE)
    set(PLATFORM_FOLDER ios)
	set(LIB_PREFIX lib)
	set(LIB_SUFFIX .a)
elseif(ANDROID)
    set(PLATFORM_FOLDER android)
	set(LIB_PREFIX lib)
	set(LIB_SUFFIX .a)
elseif(LINUX)
    set(PLATFORM_FOLDER linux)
	set(LIB_PREFIX lib)
	set(LIB_SUFFIX .a)
endif()

#2. Set Define Marco
if(WIN32)
  set(CMAKE_CXX_FLAGS_DEBUG -D_DEBUG " /MDd /Od /ZI")
  set(CMAKE_CXX_FLAGS_RELEASE -DNDEBUG " /MD /O2")
  add_definitions (-DWIN32 -D_WINDOWS)
  if(MSVC)
  	add_definitions (-D_CRT_SECURE_NO_WARNINGS -D_CRT_NON_CONFORMING_SWPRINTFS -D_SCL_SECURE_NO_WARNINGS -wd4100 -wd4127 -wd4125 -W4 -MP)
  else(MSVC)
  endif(MSVC)
elseif(APPLE)
  set(CMAKE_CXX_FLAGS_DEBUG -D_DEBUG)
  set(CMAKE_CXX_FLAGS_RELEASE -DNDEBUG)
  add_definitions(-DAPPLE)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-format-extra-args -Wno-format-security -Wno-invalid-source-encoding -Wno-reorder")
  set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libc++")
  set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++0x")
  set(CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE NO)
  set(CMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET 6.0)
  set(CMAKE_XCODE_ATTRIBUTE_TARGETED_DEVICE_FAMILY 1,2)
  set(CMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH NO)
  set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "iPhone Distribution: Chengdu Beyondtech Co., Ltd.")
  set(CMAKE_XCODE_ATTRIBUTE_PROVISIONING_PROFILE "b973b9c3-f36e-488d-b76b-0ab7d8e434d4")
elseif(ANDROID)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
else(LINUX)#Linux
    set(CMAKE_CXX_FLAGS_DEBUG -D_DEBUG)
    set(CMAKE_CXX_FLAGS_RELEASE -DNDEBUG)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -std=c++11 -O2 -Wno-format-extra-args -Wno-format-zero-length")
    add_definitions(-DLINUX -DUSE_GLOG -DBATTLE_SERVER_MODE)
endif()

add_definitions(-DASIO_SEPARATE_COMPILATION)
